### ISSUE TITLE
Server does not utilize User Agent

### ISSUE THREAD

**Issue by teeohhem** [xteve-project/xTeVe#304]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
The user-agent setting is not respected when downloading m3u lists.

**Server (please complete the following information):**
- OS FreeBSD
- Arch Intel 64 Bit
- xTeVe Version and Build latest

**To Reproduce**
1. Edit configuration and change user agent
2. Analyze network traffic using tcpdump
3. Notice the network request to fetch m3u files does not utilize the user agent

**Expected behavior**
The user agent string should be respected

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 98.0.4758.102

**Additional context**

**Comment by MCTyler** [comment]
Only applicable when using the buffer.

**Comment by AlexDias95** [comment]
@MCTyler I am having the same problem. Xteve uses indeed user-agent header when connecting to streams (after downloading m3u file) but when downloading m3u, it does not use a custom user-agent. Right now, I have downloaded a m3u list to local storage and used it but I would prefer to use m3u by URL to be always updated.

**Comment by MCTyler** [comment]
I'm not sure I understand that User-agent will be used when downloading m3u, just when streams are played VIA buffer.

**Comment by AlexDias95** [comment]
Exactly, when downloading the m3u list, some providers need user-agent to download that same list. Running streams from that list works with the custum user-agent.

**Comment by MCTyler** [comment]
Personally, I would find a different Provider if they are that picky ;)

**Comment by TheYakuzo** [comment]
The solution is to use a proxy for the request like this :
```yaml
version: '3.8'

services:
  xteve:
    # This image supports ARM64
    image: dmcallejo/xteve:latest
    container_name: xteve
    volumes:
      - /home/jerem/MediaServer/configs/xteve:/config
    environment:
      - XTEVE_PORT=34400
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    networks:
      - nginx_net
    restart: unless-stopped

  # M3U Proxy for xTeVe
  m3u-proxy:
    image: nginx:alpine
    container_name: m3u-proxy
    volumes:
      - /home/jerem/MediaServer/configs/m3u-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx_net
    restart: unless-stopped
    
networks:
  nginx_net:
    name: nginx_net
    driver: bridge
```

```conf
events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        
        location /playlist.m3u {
            proxy_pass http://my_provider.com:2103/get.php?username=xxxxxx&password=xxxxxx&output=ts&type=m3u;
            proxy_set_header User-Agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36";
            proxy_set_header Accept "*/*";
        }

        location /xmltv.xml {
            proxy_pass http://my_provider.com:2103/xmltv.php?username=xxxxxx&password=xxxxxx;
            proxy_set_header User-Agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36";
            proxy_set_header Accept "*/*";
        }
    }
}
```

And on xTeVe WebUI, just set :
XMLTV : http://m3u-proxy/xmltv.xml
Playlist : http://m3u-proxy/playlist.m3u
